"""add document storage fields

Revision ID: d21c55889954
Revises: d1f5841b149e
Create Date: 2026-06-26 02:06:12.435873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21c55889954'
down_revision: Union[str, Sequence[str], None] = 'd1f5841b149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
